[[pages]]
path = "pages/rules2.py"
name = "Rules"
icon = ":black_nib:"

[[pages]]
path = "pages/info.py"
name = "Information"
icon = ":bulb:"

[[pages]]
path = "pages/op.py"
name = "Op"
icon = ":crossed_swords:"
