[[pages]]
path = "pages/rules.py"
name = "Rules"
icon = ":black_nib:"

[[pages]]
path = "pages/rules.py"
name = "Information"
icon = ":bulb:"

[[pages]]
path = "pages/op.py"
name = "Op"
icon = ":crossed_swords:"
